# Generated by Django 4.2.1 on 2025-02-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='closed_at',
        ),
    ]
