# Generated by Django 4.2.1 on 2025-02-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_remove_issue_closed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='reporter',
            new_name='email',
        ),
    ]
