# Generated by Django 5.1.5 on 2025-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("council", "0004_alter_issue_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
